server:
 port: 8080

spring:
 datasource:
  url: jdbc:h2:mem:TEST
  username: sa
  password:
  driver-class-name: org.h2.Driver

 h2:
  console: enabled
  path: /h2

 jpa:
  hibernate:
   ddl-auto: create-update